#!/bin/bash
set -ux
git checkout -f master
git branch -D workspace &> /dev/null
set -e
# git force checkout master
git pull
git checkout $CID -b workspace
# if one of these fails recache is required
# this can be automatic ofc.
UNATTENDED=y make install-dep
UNATTENDED=y make install-ext-deps
rm -rf /var/lib/apt/lists
