#!/bin/bash

if [ $# -eq 0 ]
  then
    name='vpp-run'
  else
    name=$1
fi

state=$(docker inspect -f '{{.State.Running}}' $name)
state="$(echo -e "${state}" | tr -d '[:space:]')"
if [[ "$state" != "true" ]]; then
  docker start $name &> /dev/null
fi

shell=$(docker exec -it $name which bash)
if [ $? -ne 0 ]; then
  shell=$(docker exec -it $name which sh)
fi
if [ $? -ne 0 ]; then
  exit 1
fi
shell="$(echo -e "${shell}" | tr -d '[:space:]')"

if [ $# -gt 1 ]
then
  docker exec -it $name $shell -c ${@:2}
else
  docker exec -it $name $shell
fi
