#!/bin/bash

if [[ -z "${VPP_BOX}" ]]; then
  if [ $# -eq 0 ]
    then
     name='vpp-run'
   else
     name=$1
     args=${@:2}
  fi
else
  name=$VPP_BOX
  args=${@:1}
fi

pid=$(docker exec -it $name pidof vpp | tr -d '\r')
if [ $? -ne 0 ]; then
  exit 1
fi

if [[ -z "${args}" ]]; then
  docker exec -it $name gdb -p $pid -cd=/opt/vpp
else
  for point in "${args}"; do
    printf "br ${point}\n" > /tmp/bpoints
  done
  docker cp /tmp/bpoints $name:/tmp/bpoints
  docker exec -it $name gdb -p $pid -cd=/opt/vpp -x /tmp/bpoints
fi
