#!/bin/bash
container="vpp-run"

set -ex

if [[ -z "$VPP" ]]; then
  VPP=~/git/vpp
fi

if [[ -z "$PLUGIN" ]]; then
  PLUGIN=$VPP/src/plugins/nat
fi

cd $VPP

if [[ -z "$(git status --porcelain)" ]]; then 
    # Working directory clean
    branch=$(git rev-parse --abbrev-ref HEAD)
    git co master
    git pull
    git co $branch
    git rebase master
    if [[ $? == 0 ]]; then
        vpptool build vpp
        vpptool -plugin $PLUGIN deploy vpp
        docker exec $container bash -c "git add src/*"
        docker exec $container bash -c "git commit -a -m 'rebased'"
        docker exec $container /usr/local/bin/stage2
        exit 0
      else
        git rebase --abort
        echo "error: rebase not possible"
    fi
  else
    echo "error: working directory is not clean"
fi
exit 1
